---
- name: Mail via Ansible
  hosts: 127.0.0.1
  connection: localhost
  become: yes
  gather_facts: no
  
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      delegate_to: localhost

    - name: Start Apache service
      service:
        name: apache2
        state: started
        anabled: yes
      delegate_to: localhost

  # tasks:
  #   - name: Sending an e-mail using Gmail SMTP servers
  #     mail:
  #       host: smtp.gmail.com
  #       port: 587
  #       username: "tayoefunshile@gmail.com"
  #       password: mhgd pnif eznk ivcw
  #       to: "tayoefun@gmail.com"
  #       subject: Ansible Test Mail 2
  #       body: This mail is also from Ansible.
  #     delegate_to: localhost