---
- name: Provisioning Server & Notification
  hosts: myserver
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      register: install_apache_result

    - debug:
        var: install_apache_result.changed

    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: yes
      register: start_apache_result

    - debug:
        var: start_apache_result.changed

    - name: Sending an e-mail using mailtrap SMTP servers
      mail:
        host: smtp.mailtrap.io
        port: 587
        username: "{{ mailtrap_username }}"
        password: "{{ mailtrap_password }}"
        to: tayoefun@gmail.com
        subject: Ansible Task Completion Notification
        body: |
          The task "Install Apache" and "Start Apache" has been completed.
          Install Apache changed status: {{ install_apache_result.changed }}
          Start Apache changed status: {{ start_apache_result.changed }}
      delegate_to: localhost