---
- name: print variable value 
  hosts: all
  vars:
  tasks:
    - name: Sending an e-mail using Gmail SMTP servers
      mail:
        host: smtp.gmail.com
        port: 587
        username: Ansible Test
        password: mhgd pnif eznk ivcw
        from: tayoefunshile@gmail.com
        to: John Smith tayoefuns@gmail.com
        subject: Ansible Test Mail
        body: This mail is from Ansible.
      delegate_to: localhost